# Generated by Django 6.0.2 on 2026-02-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
